### ISSUE TITLE
Improve key CLI pages

### ISSUE THREAD

**Issue by bmicklea** [codenvy/che-docs#1]
Can you please this week do a review of a few docs pages on this branch:
https://github.com/eclipse/che/tree/che-docs/docs/_docs/use-che-as-an-ide

The pages to review:
1. All of the Che dir pages
2. The SSH page
3. The sync page
4. The CLI reference page

They all need to be improved. There are a couple things that we need to do:
1. At the beginning of the page, we need to show the user the proper docker run syntax that they would do to execute that command properly., and then:
2. We can have a short hand syntax on the other pages that do not require us showing the full docker run syntax each and every time.

In the case of the CLI reference page, we need to add in the syntax for the missing commands and add in short descriptions for each.

It's ok if you just want to push right onto my branch.

This weekend I spent a number of hours revamping this jekyll docs for Che.  The pages are all in a good spot now in the sense of us having the right pages and the right TOC, so now we can move into a mode of proper content review.

Also - at the end of the CLI Reference page, I have added a section where I start to discuss how to develop the CLI itself. I am sure we can build upon this over time.

**Comment by slemeur** [comment]
Issue has been fixed by various improvements in the docs content:
https://github.com/codenvy/che-docs/blob/master/src/main/_docs/setup/setup-cli.md
