### ISSUE TITLE
Update Debugger page with more details for GDB

### ISSUE THREAD

**Issue by slemeur** [codenvy/che-docs#48]
In the following page: https://www.google.com/url?q=https://github.com/codenvy/che-docs/blob/master/src/main/_docs/use-che-as-an-ide/ide-debug.md&sa=D&ust=1483905552882000&usg=AFQjCNFHAxtp1E0tkH5EWucS61zxRmIosA

We need to list the project types and languages where the GDB Debugger can be used.

**Comment by bmicklea** [comment]
Done in:
* https://github.com/codenvy/che-docs/pull/59
* https://github.com/codenvy/che-docs/pull/58
